apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticemicroservice-deployment
  labels:
    app: AuthenticeMicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuthenticeMicroservice  
  template:
    metadata:
      labels:
        app: AuthenticeMicroservice
    spec:
      containers:
      - name: authenticemicroservice
        image: myfirstazurecr.azurecr.io/authcr:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: authenticemicroservicesvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuthenticeMicroservice